apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml
  - manifests/cluster-secret-store.yaml
  - manifests/n8n/encryption-secret.yaml
  - manifests/db-operator/admin-secret.yaml
