apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - applications/whoami.yaml
  - applications/n8n.yaml
  - applications/cert-manager.yaml
  - applications/cluster-issuer.yaml
  - applications/external-dns.yaml
  - applications/local-path-storage.yaml
