apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: db-operator-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://db-operator.github.io/charts
    chart: db-operator
    targetRevision: db-operator-1.41.0
    helm:
      values: |
        watchNamespace: ""
        serviceMonitor:
          enabled: false
        secrets:
          gsql: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: db-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
