apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-operator-admin
  namespace: db-operator
  labels:
    app.kubernetes.io/name: db-operator
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: db-operator-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: rds/sm-postgres/root
        property: username
    - secretKey: password
      remoteRef:
        key: rds/sm-postgres/root
        property: password
    - secretKey: host
      remoteRef:
        key: rds/sm-postgres/root
        property: host
    - secretKey: port
      remoteRef:
        key: rds/sm-postgres/root
        property: port
  dataFrom:
    - find:
        path: rds/sm-postgres/root
